### ISSUE TITLE
update colors and styles for Alpheios v3.0

### ISSUE THREAD

**Issue by balmas** [alpheios-project/Gardener#1]
per styleguide

**Comment by balmas** [comment]
minor changes only made, to change the navbar color to the same background as the alpheios reader navbar, and the navigational icons to white.

**Comment by monzug** [comment]
my style guide is truncated and I am not able to download it from GitHub.  I ma not sure what I should test here. help. thanks

**Comment by balmas** [comment]
This was the instruction from the design firm (it's not actually in the style guide)

![TreeDiagram](https://user-images.githubusercontent.com/644870/63438357-261a2a00-c3fa-11e9-9b4b-5c3eefd6d5a7.png)

**Comment by monzug** [comment]
Thanks!!!

**Comment by monzug** [comment]
yes, I can see the update colors
